### ISSUE TITLE
How to cite the pipeline

### ISSUE THREAD

**Issue by neusmf** [Bushell-lab/Ribo-seq#7]
Hi!
I have used the RIbo-seq pipeline for analysing data in the lab and we are now starting to write the manuscript. Thanks for making it available, it has been very useful. I would like to know how to cite it.

Best,
Neus

**Comment by Joseph-Waldron** [comment]
Hi Neus, that's great that you've found this pipeline useful. I suggest creating a static version of all your scripts and creating a DOI for them using zenodo. You could also include the URL for this pipeline as a citation, to say where you got the scripts from. Hope this helps and good luck!
